Remove unused 'chunksize' to keep gcc-4.6 happy.
GCC 4.6 complains about chunksize being initialized and set but
never used:
  /opt/nginx-gridfs/ngx_http_gridfs_module.c:684:16: error: variable ‘chunksize’ set but not used [-Werror=unused-but-set-variable]